name: Check AWS Credentials, Generate Coverage and Scan with SonarCloud

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-aws-credentials:
    name: Check AWS Credentials
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

  test_and_sonarcloud:
    name: Run Tox for tests and SonarCloud Scan
    runs-on: ubuntu-latest
    needs: check-aws-credentials

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(which java)" >> $GITHUB_ENV

      - name: Verify Java version
        run: java -version

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install tox boto3 botocore==1.27.32
            
      - name: Run tests and generate coverage with tox
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: tox

      - name: Verify coverage.xml exists
        run: |
          if [ ! -f coverage.xml ]; then echo "coverage.xml not found"; exit 1; fi

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin"

      - name: SonarCloud Scan
        run: |
          ./sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner \
            -Dsonar.projectKey=LosBaluchis_Backend_Cafe_Balu \
            -Dsonar.organization=losbaluchis \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
